{{-- resources/views/exports/tenders-pdf.blade.php --}}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .filters {
            margin-bottom: 20px;
            padding: 10px;
            background: #f8f9fa;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f3f4f6;
        }
        .footer {
            text-align: right;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Tenders Report</h2>
        <p>Generated on: {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <div class="filters">
        <strong>Filters Applied:</strong><br>
        Date Range: {{ $filters['dateRange'] }}<br>
        Status: {{ $filters['status'] }}<br>
        Companies: {{ is_array($filters['companies']) ? implode(', ', $filters['companies']) : $filters['companies'] }}
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>Company</th>
                <th>Status</th>
                <th>Created Date</th>
                <th>Closing Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($tenders as $tender)
                <tr>
                    <td>{{ $tender->id }}</td>
                    <td>{{ $tender->title }}</td>
                    <td>{{ $tender->company->name }}</td>
                    <td>{{ ucfirst($tender->status) }}</td>
                    <td>{{ $tender->created_at->format('Y-m-d') }}</td>
                    <td>{{ $tender->end_date }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by:  | Page {PAGE_NUM} of {PAGE_COUNT}
    </div>
</body>
</html>